config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'questions#index'
  get :search, to: 'search#index'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end

  concern :rateable do
    member do
      post :like
      post :dislike
    end
  end

  concern :commentable do
    resources :comments, only: :create, shallow: true
  end

  resources :questions, except: :new, concerns: [:rateable, :commentable] do
    resources :subscriptions, only: [:create, :destroy], shallow: true

    resources :answers, only: [:create, :destroy, :update], shallow: true, concerns: [:rateable, :commentable] do
      member do
        patch :best_answer
      end
    end
  end

  resources :attachments, only: :destroy
end

app/models/question.rb
class Question < ApplicationRecord
  include Rateable
  include Commentable

  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachable
  has_many :subscriptions, dependent: :destroy

  after_create :subscribe_author

  validates :title, :body, presence: true
  scope :by_last, -> { order(created_at: :desc) }
  scope :by_latest, -> { where(created_at: 1.day.ago..Time.zone.now) }
  accepts_nested_attributes_for :attachments, reject_if: :all_blank

  def subscribe_author
    subscriptions.create(user: user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  authorize_resource

  def index
    @questions = Question.all
    respond_with @questions
  end

  def show
    respond_with Question.find(params[:id])
  end

  def create
    respond_with current_resource_owner.questions.create(question_params)
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Rated

  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_question, only: [:show, :update, :destroy]
  before_action :find_subscription, only: [:show, :update]
  after_action :publish_question, only: :create

  authorize_resource

  def index
    @question = Question.new
    @question.attachments.new
    @questions = Question.all.by_last
  end

  def show
    @answer = Answer.new
    @answer = @question.answers.new
    @answer.attachments.new
  end

  def create
    @question = current_user.questions.new(question_params)
    @question.save
  end

  def update
    @question.update(question_params)
  end

  def destroy
    @question.destroy
    flash[:notice] = 'The question is successfully deleted.'
    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file, :id, :_destroy])
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(
        partial: 'questions/question',
        locals: { question: @question }
      )
    )
  end

  def find_subscription
    @subscription = @question.subscriptions.find_by(user: current_user)
  end

  def find_question
    @question = Question.find(params[:id])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answers.html.slim
.answers
  = render question.answers.by_best

app/views/questions/_new.html.slim
= form_with model: @question, locale: true, class: 'new-question_form' do |f|
  .errors = render 'shared/errors', resource: @question
  .form-row
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-row
    = f.label :body
    = f.text_area :body, class: 'form-control'
  .form-row
    = f.fields_for :attachments, @question.attachments.build do |a|
      = render 'attachments/nested_fields', f: a
      = link_to_add_association 'Attach file', f, :attachments, partial: 'attachments/nested_fields'

  .form-row--button
    = f.submit 'Create', class: 'btn btn-success'

app/views/questions/_question.html.slim
= link_to question_path(question), class: 'question' do
  h2.question_title = question.title
  .question_body = question.body
  .question_info
    .question_date = time(question)
    .question_author = question.user.email

app/views/questions/_question_edit.html.slim
- show_comments = @question.comments.empty? ? "Comment" : "Show comments (#{@question.comments.size})"

- cache @question do
  = form_with model: @question, class: 'question_edit-form' do |f|
    = render 'shared/errors', resource: @question
    .question_title-container
      .question_title-actions
        h1.question_title = @question.title
        .question_edit-input
          p = f.label :title
          = f.text_field :title, class: 'form-control input_title'
      = render 'shared/rating', resource: @question
      - if can?(:update, @question) || can?(:destroy, @question)
        .question_actions
          a.question_actions-btn
            i.fas.fa-cog
          ul.question_actions-list
            li = link_to 'Edit question', '#', class: 'question_action question_edit-btn'
            li = link_to 'Delete question', question_path(@question), method: :delete, data: { confirm: 'Are you sure?' }, class: 'question_action question_delete-btn'
    .question_body
      .question_attr = @question.body
      .question_edit-input
        p = f.label :body
        = f.text_area :body, resize: 'disable', cols: 10, rows: 10, class: 'form-control input_body'
    .question-actions_row
      .question_subscribe-block
        - if can?(:create, Subscription) || can?(:destroy, Subscription)
          .subscribe_question
            - if !current_user.subscribed?(@question)
              = link_to 'Subscribe', question_subscriptions_path(@question), method: :post, remote: true, class: 'subscribe'
            - else
              = link_to 'Unsubscribe', subscription_path(@subscription), method: :delete, remote: true, class: 'unsubscribe'
      - if current_user
        a.question-comments_show href='#' = show_comments
      - unless @question.attachments.empty?
        a.question_attachments-show href='#' = "Show attachments (#{@question.attachments.size})"
    .question_attachments-block
      ul.question_attachments
        - @question.attachments.each do |a|
          - cache a do
            li class=("attachment_#{a.id}")
              = link_to a.file.url, class: 'question_attachments-attachment', target: '_blank' do
                = image_tag(a.file.url, class: 'question_attachments-image')
              - if can?(:destroy, a)
                = link_to attachment_path(a), method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: 'question_attachments-delete' do
                  i.fas.fa-times-circle
    .form-actions
      = f.submit 'Update', class: 'btn btn-success question_submit-form'
      = link_to 'Cancel', question_path(@question), class: 'btn btn-danger question_cancel-editing'

app/views/questions/create.js.erb
<% if @question.errors.present? %>
  $('.errors').html("<%= j render 'shared/errors', resource: @question %>");
<% else %>
  $('.errors').html('');
  $('.form-control').val('');
  $('.new-question').slideToggle();
<% end %>

app/views/questions/index.html.slim
.index_actions
  .new-question
    = render 'questions/new'
  = link_to 'Ask question', "#{current_user.nil? ? new_user_session_path : '#'}", class: 'ask_question'

.questions
  = render @questions

app/views/questions/show.html.slim
- cache @question do
  .question-container
    .question class=("question_#{@question.id}") data-id="#{@question.id}"
      = render 'questions/question_edit'
      .question-comments
        = render @question.comments
        - if can?(:create, Comment)
          = render 'comments/new', resource: @question
      = render 'questions/answers', question: @question
      - if can?(:create, Answer)
        .new_answer
          .errors
          = form_with model: [@question, @answer] do |f|
            = render 'shared/errors', resource: @answer
            = f.text_area :body, resize: 'disable', cols: 10, rows: 10, class: 'form-control input_body', placeholder: 'Write some text...'
            .form-row.answer_choose-attachment
              = f.fields_for :attachments do |a|
                = render 'attachments/nested_fields', f: a
                = link_to_add_association 'Attach file', f, :attachments, partial: 'attachments/nested_fields'
            = f.submit 'Reply', class: 'btn btn-success'

app/views/questions/update.js.erb
<% if @question.errors.present? %>
  $('.errors').html("<%= j render 'shared/errors', resource: @question %>");
<% else %>
  $('.errors').html('');
  $('.question_edit-btn, .question_attr, .question_edit-input, .question_submit-form').removeAttr('style');
  $('.question_edit-form').replaceWith("<%= j render 'questions/question_edit' %>");

  var $editBtn = $(document).find('.question_edit-btn');
  var $editQuestionForm = $(document).find('.question_edit-form');

  $editBtn.on('click', function(e) {
    e.preventDefault();
    $(this).hide();
    $('.question_attr').hide();
    $('.question_title').hide();
    $('.question_edit-input, .question_submit-form, .question_cancel-editing').show();
  });
<% end %>