config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'questions#index'
  get :search, to: 'search#index'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end

  concern :rateable do
    member do
      post :like
      post :dislike
    end
  end

  concern :commentable do
    resources :comments, only: :create, shallow: true
  end

  resources :questions, except: :new, concerns: [:rateable, :commentable] do
    resources :subscriptions, only: [:create, :destroy], shallow: true

    resources :answers, only: [:create, :destroy, :update], shallow: true, concerns: [:rateable, :commentable] do
      member do
        patch :best_answer
      end
    end
  end

  resources :attachments, only: :destroy
end

app/models/search.rb
class Search
  RESOURCES = %w(All Questions Answers Comments)

  def self.query(query, resource)
    return [] unless RESOURCES.include?(resource)
    return [] if query.empty?
    escaped_query = Riddle::Query.escape(query)
    return ThinkingSphinx.search escaped_query if resource == 'All'
    ThinkingSphinx.search escaped_query, classes: [resource.singularize.classify.constantize]
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_authorization_check

  def index
    @results = Search.query(params[:query], params[:condition])
  end
end

app/helpers/search_helper.rb
module SearchHelper
  def resource(result)
    return result if result.is_a?(Question)
    result.question
  end
end

app/views/search/_resource.html.slim
= link_to question_path(resource.question), class: 'question' do
  h2.question_title = resource.body
  .question_body = resource.question.title
  .question_info
    .question_date = time(resource.question)
    .question_author = resource.user.email

app/views/search/_search_form.html.slim
= form_tag(search_path, method: :get, class: 'search-form') do
  = text_field_tag :query, params[:query], { class: 'form-control', placeholder: 'Search' }
  = submit_tag 'Search', class: 'btn btn-primary search-btn'
  = select_tag(:condition, options_for_select(Search::RESOURCES, params[:resource]))

app/views/search/index.html.slim
- if @results.empty?
  .nothing-found Nothing Found
- else
  - @results.each do |result|
    - if result.is_a?(Question)
      = render 'questions/question', question: result
    - else
      = render 'search/resource', resource: result