config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'questions#index'
  get :search, to: 'search#index'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end

  concern :rateable do
    member do
      post :like
      post :dislike
    end
  end

  concern :commentable do
    resources :comments, only: :create, shallow: true
  end

  resources :questions, except: :new, concerns: [:rateable, :commentable] do
    resources :subscriptions, only: [:create, :destroy], shallow: true

    resources :answers, only: [:create, :destroy, :update], shallow: true, concerns: [:rateable, :commentable] do
      member do
        patch :best_answer
      end
    end
  end

  resources :attachments, only: :destroy
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Rateable
  include Commentable

  has_many :attachments, as: :attachable
  belongs_to :user
  belongs_to :question, touch: true

  validates :body, presence: true
  after_create :notify_subscribers
  scope :by_best, -> { order(best: :desc, created_at: :asc) }
  accepts_nested_attributes_for :attachments, reject_if: :all_blank

  def toggle_best!
    best_answer = question.answers.find_by(best: true)
    best_answer.update!(best: false) unless best_answer.nil?

    transaction do
      return self.update!(best: false) if self.best
      self.update!(best: true)
    end
  end

  def notify_subscribers
    AnswerNotificationsJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Rated

  before_action :authenticate_user!, only: [:create, :best_answer]
  before_action :find_question, only: :create
  before_action :find_answer, only: [:update, :best_answer, :destroy]
  after_action :publish_answer, only: :create

  authorize_resource

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    @answer.save
  end

  def update
    @answer.update(answer_params)
  end

  def best_answer
    @answer.toggle_best!
  end

  def destroy
    @answer.destroy
  end

  private

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file, :id, :_destroy])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def publish_answer
    return if @answer.errors.any?

    attachments = @answer.attachments.map do |attach|
      { id: attach.id, filename: attach.file, url: attach.file.url }
    end

    datetime = "#{view_context.time_ago_in_words(@answer.created_at)} ago"

    data = @answer.as_json(include: :attachments).merge(answer: @answer,
      user_email: @answer.user.email,
      rating: @answer.rating,
      datetime: datetime)

    ActionCable.server.broadcast("question-#{@question.id}", data: data)
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  authorize_resource
  before_action :find_question, only: [:index, :create]

  def index
    respond_with @question.answers
  end

  def show
    @answer = Answer.find(params[:id])
    respond_with @answer
  end

  def create
    respond_with @question.answers.create(answer_params.merge(user: current_resource_owner))
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def find_question
    @question = Question.find(params[:question_id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- show_comments = answer.comments.empty? ? "Comment" : "Show comments (#{answer.comments.size})"


- cache answer do
  .answer class=("answer_#{answer.id}") class=('best_answer' if answer.best?)
    .answer_row
      .answer_container
        .answer_body = answer.body
        = form_with model: answer, remote: true, class: 'answer_edit-form', id: "edit-answer-#{answer.id}" do |f|
          = f.label :body
          = f.text_area :body, class: 'form-control'
          = f.submit 'Update', class: 'btn btn-success answer_update'
        .answer_info
          .answer_date = time(answer)
          .answer_author = answer.user.email
      .answer_actions
        = render 'shared/rating', resource: answer
        - if can?(:best_answer, answer)
          .answer_toggle-best
            = link_to "#{answer.best ? 'Remove best flag' : 'Mark as best'}", best_answer_answer_url(answer), class: 'btn btn-info answer_best', method: :patch, remote: true
        - if can?(:update, answer) || can?(:destroy, answer)
          .answer_settings
            a.answer_actions-btn
              i.fas.fa-cog
          ul.answer_actions-list
            li = link_to 'Edit answer', '', class: 'answer_edit-btn', data: { answer_id: answer.id }
            li = link_to 'Delete answer', answer, method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: 'answer_delete-btn'
    .answer-actions_row
      a.answer-comments_show href='#' = show_comments
      - unless answer.attachments.empty?
        a.answer_attachments-show href='#' = "Show attachments (#{answer.attachments.size})"
    .answer_attachments-block
      ul.answer_attachments
        - answer.attachments.each do |a|
          li class=("attachment_#{a.id}")
            = link_to a.file.url, class: 'answer_attachments-attachment', target: '_blank' do
              = image_tag(a.file.url, class: 'answer_attachments-image')
            - if can?(:destroy, a)
              = link_to attachment_path(a), method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: 'answer_attachments-delete' do
                i.fas.fa-times-circle
    .answer_comments-block
      .answer-comments
        = render answer.comments
        - if can?(:create, Comment)
          = render 'comments/new', resource: answer

app/views/answers/best_answer.js.erb
<% if @answer.errors.present? %>
  $('.errors').html("<%= j render 'shared/errors', resource: @answer %>");
<% else %>
  $('.answers').replaceWith("<%= j render 'questions/answers', question: @answer.question %>");
  $('.errors').html('');
<% end %>

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  $('.errors').html("<%= j render 'shared/errors', resource: @answer %>");
<% else %>
  $('.answers').append('<%= j render @answer %>');
  $('.errors').html('');
  $('.input_body').val('');
  $('.nested-fields').remove();
<% end %>

app/views/answers/destroy.js.erb
$('.answer_<%= @answer.id %>').remove();

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  $('.errors').html("<%= j render 'shared/errors', resource: @answer %>");
<% else %>
  $('.answer.answer_<%= @answer.id %>').replaceWith('<%= j render @answer %>');
  $('.errors').html('');
<% end %>